/**
 * @module @yoltra/devtools-protocol
 */

import type { ExtensionCapabilities, HubCapabilities, StoreCapabilities } from "./capabilities";
import type { DevtoolsRole } from "./roles";

/**
 * Sent by a client immediately after WebSocket connection.
 *
 * @remarks
 * The hub validates the protocol version and responds with
 * a {@link HandshakeResponse}. Connections that do not handshake
 * within 5 seconds are terminated.
 *
 * Exactly one of `store` or `extension` must be present depending
 * on the declared {@link DevtoolsRole}.
 *
 * @example
 * ```ts
 * import type { HandshakeRequest } from "@yoltra/devtools-protocol";
 *
 * const req: HandshakeRequest = {
 *   type: "HANDSHAKE_REQUEST",
 *   protocolVersion: "1.0.0",
 *   role: DevtoolsRole.STORE,
 *   store: {
 *     id: crypto.randomUUID(),
 *     name: "myStore",
 *     capabilities: { replay: true, stateSnapshot: true, emit: false },
 *   },
 * };
 * ```
 *
 * @public
 */
export interface HandshakeRequest {
  type: "HANDSHAKE_REQUEST";
  /** Semver protocol version the client supports. */
  protocolVersion: string;
  /** Role this client will assume. */
  role: DevtoolsRole;
  /** Present only when `role` is `STORE`. */
  store?: {
    /** UUID generated by the wrapper. Persists across reconnections. */
    id: string;
    /** Human-readable store name from `createStore({ name })`. */
    name: string;
    /** Store-side feature capabilities. */
    capabilities: StoreCapabilities;
  };
  /** Present only when `role` is `EXTENSION`. */
  extension?: {
    /** UUID identifying this extension instance. */
    id: string;
    /** Display name (e.g., "VSCode DevTools", "Browser DevTools"). */
    name: string;
    /** Extension-side feature capabilities. */
    capabilities: ExtensionCapabilities;
  };
}

/**
 * Hub response to a {@link HandshakeRequest}.
 *
 * @remarks
 * When `success` is `false`, the `error` field contains a human-readable
 * reason (e.g., incompatible protocol version). The client should close
 * the WebSocket and report the error to the user.
 *
 * @public
 */
export interface HandshakeResponse {
  type: "HANDSHAKE_RESPONSE";
  /** Whether the handshake was successful. */
  success: boolean;
  /** The negotiated protocol version (may differ from requested). */
  negotiatedVersion: string;
  /** Hub-side capabilities. */
  hubCapabilities: HubCapabilities;
  /** Error message when `success` is `false`. */
  error?: string;
}
