/**
 * @module @yoltra/devtools-protocol
 */

/**
 * JSON Patch operation types per [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902).
 *
 * @remarks
 * Only `add`, `remove`, and `replace` are generated by the devtools
 * wrapper today; `move`, `copy`, and `test` are included for
 * forward-compatibility with future protocol extensions.
 *
 * @public
 */
export type JsonPatchOp = "add" | "remove" | "replace" | "move" | "copy" | "test";

/**
 * A single JSON Patch operation per RFC 6902.
 *
 * @remarks
 * Paths use JSON Pointer syntax (RFC 6901), e.g., `"/counter/value"`.
 * An array of these operations is carried inside every {@link StoreEvent}
 * message, enabling extensions to reconstruct state incrementally
 * without requesting a full snapshot.
 *
 * @example
 * ```ts
 * import type { JsonPatch } from "@yoltra/devtools-protocol";
 *
 * const patch: JsonPatch = {
 *   op: "replace",
 *   path: "/counter/value",
 *   value: 42,
 * };
 * ```
 *
 * @public
 */
export interface JsonPatch {
  /** The operation to perform. */
  op: JsonPatchOp;
  /** Target path in JSON Pointer format (RFC 6901). */
  path: string;
  /** Value for `add`, `replace`, and `test` operations. */
  value?: unknown;
  /** Source path for `move` and `copy` operations. */
  from?: string;
}
