import type { DeepReadonly, Emit } from "@yoltra/core";
import type { UseAtomicProp, UseAtomicProps } from "@yoltra/react";
import { createHooks } from "@yoltra/react";
import { AppStoreContext } from "./Store.context";
import type { RootReducerKeys, RootReducerState, tAppEM, tAppStore } from "./store";

/**
 * All typed hooks generated by createHooks. */
const hooks = createHooks<RootReducerKeys, RootReducerState, tAppEM>(AppStoreContext);

/**
 * Returns the app store instance. */
export const useStore: () => tAppStore = hooks.useStore;

/**
 * Returns the typed `emit` function for dispatching events. */
export const useEmit: () => Emit<tAppEM> = hooks.useEmit;

/**
 * Subscribes to derived state via a selector function.
 * Re-renders when selected value changes (checked via `isEqual`). */
export const useSelector: <T>(
  selector: (state: DeepReadonly<RootReducerState>) => T,
  isEqual?: (a: T, b: T) => boolean,
) => T = hooks.useSelector;

/**
 * Fine-grained subscription to a single property path in a reducer slice.
 * Only re-renders when that specific path changes. */
export const useAtomicProp: UseAtomicProp<RootReducerKeys, RootReducerState> =
  hooks.useAtomicProp;

/**
 * Fine-grained subscription to multiple property paths.
 * Re-renders only when any of the specified paths change. */
export const useAtomicProps: UseAtomicProps<RootReducerKeys, RootReducerState> =
  hooks.useAtomicProps;

/**
 * Shallow equality comparator for objects.
 * Compares enumerable keys using Object.is. */
export const shallowEqual: <T extends Record<string, never>>(a: T, b: T) => boolean =
  hooks.shallowEqual;
